#!/usr/bin/env python3
"""
t3_hunt.py -- direct glider hunt in the single-field W=1 sector.

A third instrument, independent of both deciders: run the one-bit CA forward
from many seeds and detect translation-recurrence.  For a finite non-empty S
the set  G(S) = {(t,x) : Phi^t S = sigma^x S}  is (once Phi is invertible on
the orbit) a rank-1 subgroup of Z^2 meeting {0} x Z trivially, so it is
generated by a unique (p0, d0) with p0 >= 1 -- the MINIMAL period and the
displacement per minimal period.  This routine returns exactly that (p0,d0).

Its purpose is to produce certified LOWER bounds on max |d0|, which is what
refutes a claimed cap.  Upper bounds come from t3_decide.py.
"""
from __future__ import annotations

import os
import random
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.dirname(HERE))

from t3_core import rule_table, step_set                      # noqa: E402


def norm(S):
    lo = min(S)
    return frozenset(x - lo for x in S), lo


def hunt(S0, tab, max_steps=400, max_card=400, max_span=600):
    """Classify one orbit.  Returns (kind, p0, d0, span) with kind in
    EXTINCT / FIXED / CYCLE / GLIDER / GROW / OPEN."""
    S = set(S0)
    seen = {}
    for t in range(max_steps):
        if not S:
            return ("EXTINCT", None, None, None)
        if len(S) > max_card or max(S) - min(S) > max_span:
            return ("GROW", None, None, None)
        k, lo = norm(S)
        if k in seen:
            t0, lo0 = seen[k]
            p, d = t - t0, lo - lo0
            if d == 0:
                return ("FIXED" if p == 1 else "CYCLE", p, 0, max(S) - min(S) + 1)
            return ("GLIDER", p, d, max(S) - min(S) + 1)
        seen[k] = (t, lo)
        S = step_set(S, tab)
    return ("OPEN", None, None, None)


def hunt_class(cls, mode="parity", nseed=600, rng=None, max_steps=400,
               seed_span=14):
    """Best |d0| found over a seed sample, plus all (p0,d0) seen."""
    tab = rule_table(cls, mode)
    rng = rng or random.Random(12345)
    found = {}
    # systematic small seeds first
    seeds = []
    for m in range(1, 1 << 8):
        seeds.append({i for i in range(8) if (m >> i) & 1})
    for _ in range(nseed):
        n = rng.randrange(1, seed_span + 1)
        seeds.append({rng.randrange(0, seed_span) for _ in range(n)})
    for S in seeds:
        if not S:
            continue
        kind, p, d, span = hunt(S, tab, max_steps=max_steps)
        if kind == "GLIDER":
            key = (p, d)
            if key not in found or span < found[key][1]:
                found[key] = (sorted(S), span)
    return found


def main():
    from t3_core import all_parity_classes, all_or_classes
    mode = sys.argv[1] if len(sys.argv) > 1 else "parity"
    nseed = int(sys.argv[2]) if len(sys.argv) > 2 else 400
    classes = all_parity_classes() if mode == "parity" else all_or_classes()
    rng = random.Random(2026)
    best = {}
    for cls in classes:
        f = hunt_class(cls, mode, nseed=nseed, rng=rng)
        for (p, d), (S, span) in f.items():
            if abs(d) > abs(best.get("maxd", (0, None, None, None))[0]) \
                    if isinstance(best.get("maxd"), tuple) else True:
                pass
        if f:
            best[cls] = f
    allpd = {}
    for cls, f in best.items():
        for (p, d), (S, span) in f.items():
            if (p, d) not in allpd or span < allpd[(p, d)][2]:
                allpd[(p, d)] = (cls, S, span)
    print("mode=%s  classes with gliders: %d / %d" % (mode, len(best),
                                                      len(classes)))
    print("distinct minimal (p0,d0) found: %d" % len(allpd))
    for (p, d) in sorted(allpd, key=lambda k: (abs(k[1]), k[0])):
        cls, S, span = allpd[(p, d)]
        print("  p0=%2d d0=%+3d   class=%s  seed=%s span=%d"
              % (p, d, cls, S, span))
    mx = max(abs(d) for (p, d) in allpd) if allpd else 0
    print("MAX |d0| found by hunting: %d" % mx)


if __name__ == "__main__":
    main()
