/* xengine.js — the cross-amendment engine of nomodynamics, for the demo.
 *
 * Mirrors xnomos.py exactly (see xengine.test.js, which checks both against
 * vectors generated by the Python reference).  Inlined into the demo page.
 *
 * A constitution:  {rules:[[a,b,c],...], targets:[t,...], dim:1|2, mod:null|m}
 *   1-D offsets are integers; 2-D offsets are [dx,dy] pairs.
 *   targets[k] is a kind index, or an array of kind indices (multi-target).
 * A state: Map key -> bitmask of kinds present.  Key is the cell itself in 1-D
 *   (a number) and "x,y" in 2-D.
 * Modes: "parity" (odd number of toggles flips), "or" (>=1 flips),
 *   "super" / "super_or" (supersession: enact own kind on empty ground,
 *   else clear the whole cell).
 */
(function (root) {
  "use strict";

  function makeOps(C) {
    if (C.dim === 2) {
      return {
        add: function (k, off) {
          var p = k.split(",");
          return (+p[0] + off[0]) + "," + (+p[1] + off[1]);
        }
      };
    }
    if (C.mod) {
      var m = C.mod;
      return { add: function (k, off) { return ((k + off) % m + m) % m; } };
    }
    return { add: function (k, off) { return k + off; } };
  }

  /* Citation guards (chapter three): C.guards[k] = [g, h].  null/undefined
   * means "any law" -- the founding occupancy semantics.  A kind index names
   * that particular kind. */
  function guardOf(C, k) {
    return (C.guards && C.guards[k]) || [null, null];
  }
  function holds(S, x, key) {
    if (x === null || x === undefined) return S.has(key);
    return ((S.get(key) || 0) >> x & 1) === 1;
  }
  function enabled(S, C, ops, cell, k) {
    var r = C.rules[k], g = guardOf(C, k);
    if (!holds(S, g[0], ops.add(cell, r[0]))) return false;
    return !holds(S, g[1], ops.add(cell, r[1]));
  }

  function targetsOf(C, k) {
    var t = C.targets ? C.targets[k] : k;
    return Array.isArray(t) ? t : [t];
  }

  function step(S, C, mode) {
    mode = mode || "parity";
    var ops = makeOps(C);
    if (mode === "super" || mode === "super_or") {
      return stepSuper(S, C, ops, mode === "super_or");
    }
    var tog = new Map();          // key|kind -> parity or count-flag
    S.forEach(function (mask, cell) {
      for (var k = 0; k < C.rules.length; k++) {
        if (!(mask >> k & 1)) continue;
        if (!enabled(S, C, ops, cell, k)) continue;
        var j = ops.add(cell, C.rules[k][2]);
        var tg = targetsOf(C, k);
        for (var q = 0; q < tg.length; q++) {
          var key = j + "|" + tg[q];
          tog.set(key, mode === "or" ? 1 : ((tog.get(key) || 0) ^ 1));
        }
      }
    });
    var out = new Map(S);
    tog.forEach(function (v, key) {
      if (!v) return;
      var ix = key.lastIndexOf("|");
      var cell = key.slice(0, ix), k = +key.slice(ix + 1);
      if (C.dim !== 2) cell = +cell;
      var nm = (out.get(cell) || 0) ^ (1 << k);
      if (nm) out.set(cell, nm); else out.delete(cell);
    });
    return out;
  }

  function stepSuper(S, C, ops, orResolve) {
    var enact = new Map(), clearPar = new Map(), clearAny = new Set();
    S.forEach(function (mask, cell) {
      for (var k = 0; k < C.rules.length; k++) {
        if (!(mask >> k & 1)) continue;
        if (!enabled(S, C, ops, cell, k)) continue;
        var j = ops.add(cell, C.rules[k][2]);
        if (S.has(j)) {
          clearPar.set(j, (clearPar.get(j) || 0) ^ 1);
          clearAny.add(j);
        } else {
          enact.set(j, (enact.get(j) || 0) | (1 << k));
        }
      }
    });
    var out = new Map(S);
    (orResolve ? clearAny : new Set(
      Array.from(clearPar.keys()).filter(function (j) { return clearPar.get(j); })
    )).forEach(function (j) { out.delete(j); });
    enact.forEach(function (m, j) { out.set(j, (out.get(j) || 0) | m); });
    out.forEach(function (m, j) { if (!m) out.delete(j); });
    return out;
  }

  function activeLaws(S, C) {
    var ops = makeOps(C), out = [];
    S.forEach(function (mask, cell) {
      for (var k = 0; k < C.rules.length; k++) {
        if (!(mask >> k & 1)) continue;
        if (enabled(S, C, ops, cell, k)) out.push([cell, k]);
      }
    });
    return out;
  }

  function card(S) {
    var n = 0;
    S.forEach(function (m) { for (var v = m; v; v &= v - 1) n++; });
    return n;
  }

  function seed(pairs, C) {
    var S = new Map();
    pairs.forEach(function (p) {
      var cell = C && C.dim === 2 ? p[0] + "," + p[1] : p[0];
      var k = C && C.dim === 2 ? p[2] : p[1];
      S.set(cell, (S.get(cell) || 0) | (1 << k));
    });
    return S;
  }

  /* --- impermanence: a law lapses unless re-enacted (see sunset/sunset.py) --
   * Effects are ENACTMENTS, not toggles.  `ages` maps "cell|kind" to the number
   * of steps since that law was last enacted; a law survives while age < tau.
   * Returns {S, ages}. */
  function stepSunset(S, C, tau, ages) {
    var ops = makeOps(C);
    tau = tau || 1;
    if (!ages) {
      ages = new Map();
      S.forEach(function (mask, cell) {
        for (var k = 0; k < C.rules.length; k++)
          if (mask >> k & 1) ages.set(cell + "|" + k, 0);
      });
    }
    var enacted = new Set();
    S.forEach(function (mask, cell) {
      for (var k = 0; k < C.rules.length; k++) {
        if (!(mask >> k & 1)) continue;
        if (!enabled(S, C, ops, cell, k)) continue;
        var j = ops.add(cell, C.rules[k][2]), tg = targetsOf(C, k);
        for (var q = 0; q < tg.length; q++) enacted.add(j + "|" + tg[q]);
      }
    });
    var out = new Map(), na = new Map();
    enacted.forEach(function (key) {
      var ix = key.lastIndexOf("|");
      var cell = key.slice(0, ix), k = +key.slice(ix + 1);
      if (C.dim !== 2) cell = +cell;
      out.set(cell, (out.get(cell) || 0) | (1 << k));
      na.set(key, 0);
    });
    S.forEach(function (mask, cell) {
      for (var k = 0; k < C.rules.length; k++) {
        if (!(mask >> k & 1)) continue;
        var key = cell + "|" + k;
        if (enacted.has(key)) continue;
        var age = (ages.get(key) || 0) + 1;
        if (age < tau) {
          out.set(cell, (out.get(cell) || 0) | (1 << k));
          na.set(key, age);
        }
      }
    });
    return {S: out, ages: na};
  }

  var API = { step: step, activeLaws: activeLaws, card: card, seed: seed,
              stepSunset: stepSunset };
  if (typeof module !== "undefined" && module.exports) module.exports = API;
  else root.XN = API;
})(typeof globalThis !== "undefined" ? globalThis : this);
